apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-argelor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-argelor
  template:
    metadata:
      labels:
        app: mongo-argelor
    spec:
      containers:
        - name: mongo-argelor
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-argelor
spec:
  selector:
    app: mongo-argelor
  ports:
    - protocol: TCP
      port: 27018
      targetPort: 27017
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-argelor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-argelor
  template:
    metadata:
      labels:
        app: mongo-argelor
    spec:
      containers:
        - name: mongo-argelor
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-argelor
spec:
  selector:
    app: mongo-argelor
  ports:
    - protocol: TCP
      port: 27018
      targetPort: 27017
