apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-vate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-vate
  template:
    metadata:
      labels:
        app: mongo-vate
    spec:
      containers:
        - name: mongo-vate
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-vate
spec:
  selector:
    app: mongo-vate
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
