apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-vate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-vate
  template:
    metadata:
      labels:
        app: provider-vate
    spec:
      containers:
        - name: provider-vate
          image: provider-vate:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: MONGO_URI
              value: mongodb://mongo-vate:27017/provider-vate-db

---
apiVersion: v1
kind: Service
metadata:
  name: provider-vate
spec:
  selector:
    app: provider-vate
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
